### ISSUE TITLE
Visualize metrics for a specific Scenario 

### ISSUE THREAD

**Issue by yT0n1** [BPChain/meta#79]
To compare the performance of different blockchains I want a visualization of the metrics for a specific predefined scenario. 
- [x] User can select scenario out of a list (for now just containing one scenario) and run it.
- [x] Scenario/Smart-Contract runs on Xain/Private-Ethereum/Multichain
- [x] User can compare important metrics. At least "Transaction Time" and two others.
- [x] There is a comprehensible description of the scenario
